# Generated by Django 4.1.7 on 2023-06-19 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Categoria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Posts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "post_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Date"
                    ),
                ),
                ("post_content", models.TextField(verbose_name="Content")),
                ("post_excerpt", models.TextField(verbose_name="Excerpt")),
                (
                    "post_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="post_img/%Y/%m/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "post_published",
                    models.BooleanField(default=False, verbose_name="Published"),
                ),
                (
                    "post_author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "post_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="posts.categoria",
                        verbose_name="Category",
                    ),
                ),
            ],
        ),
    ]
